project_id = "vaxjjcdbhoejcmvuyunv"

[functions.analyze-meal]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.ai-coach]
verify_jwt = false

[functions.estimate-nutrition]
verify_jwt = false
